spring:
  datasource:
    url: jdbc:h2:mem:autostock;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  batch:
    jdbc:
      initialize-schema: always

kis:
  base-url: https://openapi.koreainvestment.com:9443
  app-key: YOUR_APP_KEY
  app-secret: YOUR_APP_SECRET
  cano: "12345678" # 계좌번호
  acnt-prdt-cd: "01" # 계좌상품코드.
  cust-type: "P"
